name:                SharingIsCaring
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/alexknvl/practical-observable-sharing
license:             BSD3
author:              Alexander Konovalov
maintainer:          alex.knvl@gmail.com
copyright:           2019 Alexander Konovalov
category:            Web
extra-source-files:
- README.md

default-extensions:
  - ExistentialQuantification
  - ConstraintKinds
  - KindSignatures
  - RankNTypes
  - ScopedTypeVariables
  - DeriveFunctor
  - DeriveTraversable
  - BangPatterns
  - FunctionalDependencies
  - InstanceSigs
  - StandaloneDeriving
  - ImpredicativeTypes
  - FlexibleInstances
  - FlexibleContexts
  - LambdaCase
  - TypeFamilies
  - TupleSections

dependencies:
  - base >= 4.7 && < 5
  - containers
  - unordered-containers
  - mtl
  - profunctors
  - hashable
  - ghc-heap
  - recursion-schemes

executables:
  SharingIsCaring:
    source-dirs:      src
    main:             Main.hs
